### ISSUE TITLE
What if my es does not need username and password?

### ISSUE THREAD

**Issue by c-box** [TheScienceMuseum/elastic-wikidata#13]
Is the username and password must be required?
I pass a blank string and it can't work.
`ValueError: Missing Elasticsearch credentials: {'ELASTICSEARCH_USER', 'ELASTICSEARCH_PASSWORD'}`

**Comment by kdutia** [comment]
Hi @c-box, sorry for the late reply. I hadn't considered Elasticsearch instances without a username and password that aren't running on localhost. You should be able to comment out lines 85-89  in `elastic_wikidata.dump_to_es` as follows:

``` py
if "ELASTICSEARCH_CLUSTER" in self.es_credentials:
            print(
                f"Connecting to Elasticsearch at {self.es_credentials['ELASTICSEARCH_CLUSTER']}"
            )
            self.es = Elasticsearch(
                # COMMENT OUT THE LINES BELOW
                # [self.es_credentials["ELASTICSEARCH_CLUSTER"]],
                # http_auth=(
                #     self.es_credentials["ELASTICSEARCH_USER"],
                #     self.es_credentials["ELASTICSEARCH_PASSWORD"],
                # ),
            )
```

**Comment by c-box** [comment]
Thanks a lot!
