### ISSUE TITLE
mapping error: Elasticsearch version?

### ISSUE THREAD

**Issue by kgeographer** [TheScienceMuseum/elastic-wikidata#17]
I have Elasticsearch 6.6 installed on a mac, running fine with several indexes. Trying now to test elastic-wikidata in Python 3.74 with the humans sparql query and a limit of 100.

`ew query -p ./humans.rq -i wd -l 100`

I get this error: `'Validation Failed: 1: type is missing;2: type is missing; ... etc.`

I thought it had to do with the mapping, so I just tried creating an index independently, with python as I normally do,
`es.indices.create(index='wd', ignore=400, body=mappings)`, using the mappings object found in dump_to_es.py:96

I get this error:
`{'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Root mapping definition has unsupported parameters:  [aliases : {copy_to=labels_aliases, type=text}] [labels_aliases : {store=true, type=text}] [labels : {copy_to=labels_aliases, type=text}]'}], ...`

Wondering if this is a version issue - what ES versions do you support? Tips to get this going? Thanks

**Comment by kdutia** [comment]
Hi Karl. Can you tell me more about the `Validation Failed` error - does the error message say where it comes from?

I'm guessing you're right and it's to do with the mapping creation in an older Elasticsearch version. I'm running Elasticsearch 7.8.0 and haven't tested it with any older versions - you try to run a newer ES version inside Docker or on a remote machine?

**Comment by kgeographer** [comment]
The full error reads: 
```elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing; 2: type is missing; ... 100: type is missing;``` ("type is missing" repeats 100 times).

But it is preceded by several deprecation warnings:
```ElasticsearchDeprecationWarning: field [representative_point] referenced in context [location] is not defined in the mapping```
```ElasticsearchDeprecationWarning: Setting index.mapper.dynamic is deprecated since indices may not have more than one type anymore.```
```ElasticsearchDeprecationWarning: field [location.coordinates] referenced in context [location] is not defined in the mapping```

I don't understand why there's reference to location and representative point, or what `context [location]` refers to. In any case, I thought deprecation warnings are not breaking. Not an ES expert at all; several indexes in 6.6 are working well, but I fear version must be ruled out, as you say. I eventually want to generate a fresh index monthly on cron, so I will revisit this after I've updated ES.

In the meantime, I have used wikibase-dump-filter to get 8m or so simplified JSON records, which I will try to index through 'normal' means in python.

thanks, Karl

**Comment by kdutia** [comment]
sounds wise!
