### ISSUE TITLE
How does it compare to CirrusSearch?

### ISSUE THREAD

**Issue by Abbe98** [TheScienceMuseum/elastic-wikidata#3]
Wikidata's Elasticsearch instances can be queried by the MediaWiki API using CirrusSearch, but this is entirely left out of the "Why" section of the README...

Would be interesting to see query examples one can't do with CirrusSearch.

**Comment by kdutia** [comment]
Thanks for the comment @Abbe98. My main reason for creating this was that we need to do bulk text searches of Wikidata (i.e. not with rate limiting), and sending the dumps to our own Elasticsearch instance was easier than setting up our own Wikidata instance.

I hadn't seen CirrusSearch before hence leaving it out of the readme, apologies! 

I'll look into updating the README with a link to CirrusSearch as an alternative to this repo once I've read about it.

**Comment by kdutia** [comment]
See updated README
